build: false

environment:
  matrix:
    - PYTHON: "C:/Python27"

os:
  - unstable

platform:
  - x86

install:
  - "%PYTHON%/python create_venv.py --with-optional-packages venv"
  - "venv/Scripts/activate.bat"

before_test:
  # Run pep8 on all except the checked out marionette-client folder
  - "%PYTHON%/Scripts/pep8 --max-line-length=99 --exclude=client ."

  # Download latest Firefox Nightly, which is compatible with the Marionette client version used
  - "%PYTHON%/Scripts/mozdownload -t daily -p win32 --destination %CD%/firefox-installer.exe"
  - "%PYTHON%/Scripts/mozinstall firefox-installer.exe"

test_script:
  # Bug 1125732 - Workaround for hang during uninstall of the build
  # - "%PYTHON%/Scripts/firefox-ui-tests --installer firefox-installer.exe"
  # Run in non-e10s mode
  - "%PYTHON%/Scripts/firefox-ui-tests --binary firefox-installer/firefox.exe

  # Run in e10s mode
  - "%PYTHON%/Scripts/firefox-ui-tests --binary firefox-installer/firefox.exe --e10s

notifications:
  email:
    #- dev-automation@lists.mozilla.org
  irc:
    #- "irc.mozilla.org#automation"
